#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m config debug_output on

yabai -m config mouse_follows_focus off
#yabai -m config focus_follows_mouse autoraise

yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config window_border off

yabai -m config layout bsp
yabai -m config top_padding 15
yabai -m config bottom_padding 15
yabai -m config left_padding 15
yabai -m config right_padding 15
yabai -m config window_gap 10

yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='Preferences$' manage=off topmost=on
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add title="Software Update$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add title='Archive Utility$' manage=off
yabai -m rule --add title='Bin$' manage=off
yabai -m rule --add title="^Opening*" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

yabai -m config --space 2 layout float
yabai -m config --space 4 layout float
